Repository milan1750/php-todo-app, pull requests merged in 2023-05, with the labels that each got.

#1 Views added for login, register, homepage
  src/views/homepage.php
  src/views/loginpage.php
  src/views/registerpage.php
Labels: good first issue, ready to merge

#3 Revert "inital design done"
  assets/css/style.css
  assets/images/logo.png
  assets/images/logout.png
Labels: enhancement

#4 Test Case added
  tests/ValidationTest.php
Labels: enhancement, ready to merge

#6 GitHub action added for tests
  .github/workflows/deploy.yml
  .gitignore
  README.md
  composer.json
Labels: enhancement

#7 Add password validation
  src/Validation.php
  tests/ValidationTest.php
Labels: enhancement
